-- Seed data for Big Brother Fantasy League

-- Insert houseguests
INSERT INTO houseguests (slug, "firstName", "lastName", "photoUrl", bio, status) VALUES
('adrian-rocha', 'Adrian', 'Rocha', 'https://example.com/adrian.jpg', 'Adrian is a charismatic contestant known for their strategic gameplay.', 'IN'),
('ashley-hollis', 'Ashley', 'Hollis', 'https://example.com/ashley.jpg', 'Ashley brings determination and social skills to the house.', 'IN'),
('brittany-hoopes', 'Brittany', 'Hoopes', 'https://example.com/brittany.jpg', 'Brittany is a competitive player with a strong social game.', 'IN'),
('cameron-hardin', 'Cameron', 'Hardin', 'https://example.com/cameron.jpg', 'Cameron is known for their analytical approach to the game.', 'IN'),
('cory-wurtenberger', 'Cory', 'Wurtenberger', 'https://example.com/cory.jpg', 'Cory brings energy and enthusiasm to the Big Brother house.', 'IN'),
('felicia-cannon', 'Felicia', 'Cannon', 'https://example.com/felicia.jpg', 'Felicia is a strategic player with a strong social game.', 'IN'),
('jag-bains', 'Jag', 'Bains', 'https://example.com/jag.jpg', 'Jag is a competitive player who excels in physical challenges.', 'IN'),
('jared-fields', 'Jared', 'Fields', 'https://example.com/jared.jpg', 'Jared brings charisma and strategic thinking to the game.', 'IN'),
('jessica-grimm', 'Jessica', 'Grimm', 'https://example.com/jessica.jpg', 'Jessica is a determined player with strong social connections.', 'IN'),
('kirsten-elwin', 'Kirsten', 'Elwin', 'https://example.com/kirsten.jpg', 'Kirsten is known for their strategic gameplay and social skills.', 'IN'),
('luke-valentine', 'Luke', 'Valentine', 'https://example.com/luke.jpg', 'Luke brings humor and strategy to the Big Brother house.', 'IN'),
('matt-klotz', 'Matt', 'Klotz', 'https://example.com/matt.jpg', 'Matt is a competitive player with strong physical abilities.', 'IN'),
('mecole-haywood', 'Mecole', 'Haywood', 'https://example.com/mecole.jpg', 'Mecole is a strategic player with excellent social skills.', 'IN'),
('red-utley', 'Red', 'Utley', 'https://example.com/red.jpg', 'Red brings experience and strategic thinking to the game.', 'IN'),
('reilly-smedley', 'Reilly', 'Smedley', 'https://example.com/reilly.jpg', 'Reilly is a competitive player with strong social connections.', 'IN');

-- Insert sample weeks (you can modify these as the season progresses)
INSERT INTO weeks (week, "hohCompetition", "povCompetition", "blockbusterCompetition") VALUES
(1, 'Endurance Challenge', 'Veto Competition', 'Blockbuster Twist'),
(2, 'Physical Challenge', 'Mental Challenge', 'Power Shift'),
(3, 'Social Challenge', 'Endurance Test', 'Game Changer'),
(4, 'Mental Challenge', 'Physical Test', 'Wild Card'),
(5, 'Endurance Challenge', 'Social Game', 'Power Play'),
(6, 'Physical Challenge', 'Mental Test', 'Game Breaker'),
(7, 'Social Challenge', 'Endurance Test', 'Power Move'),
(8, 'Mental Challenge', 'Physical Game', 'Wild Twist'),
(9, 'Endurance Challenge', 'Social Test', 'Game Changer'),
(10, 'Physical Challenge', 'Mental Game', 'Power Shift'),
(11, 'Social Challenge', 'Endurance Game', 'Wild Card'),
(12, 'Mental Challenge', 'Physical Test', 'Game Breaker'),
(13, 'Endurance Challenge', 'Social Game', 'Power Move'),
(14, 'Physical Challenge', 'Mental Test', 'Wild Twist'),
(15, 'Social Challenge', 'Endurance Game', 'Game Changer'),
(16, 'Mental Challenge', 'Physical Game', 'Power Shift'),
(17, 'Endurance Challenge', 'Social Test', 'Wild Card'),
(18, 'Physical Challenge', 'Mental Game', 'Game Breaker'),
(19, 'Social Challenge', 'Endurance Test', 'Power Move'),
(20, 'Mental Challenge', 'Physical Game', 'Wild Twist'),
(21, 'Endurance Challenge', 'Social Game', 'Game Changer'),
(22, 'Physical Challenge', 'Mental Test', 'Power Shift'),
(23, 'Social Challenge', 'Endurance Game', 'Wild Card'),
(24, 'Mental Challenge', 'Physical Test', 'Game Breaker'),
(25, 'Endurance Challenge', 'Social Game', 'Power Move'),
(26, 'Physical Challenge', 'Mental Game', 'Wild Twist'),
(27, 'Social Challenge', 'Endurance Test', 'Game Changer'),
(28, 'Mental Challenge', 'Physical Game', 'Power Shift'),
(29, 'Endurance Challenge', 'Social Test', 'Wild Card'),
(30, 'Physical Challenge', 'Mental Game', 'Game Breaker'),
(31, 'Social Challenge', 'Endurance Game', 'Power Move'),
(32, 'Mental Challenge', 'Physical Test', 'Wild Twist'),
(33, 'Endurance Challenge', 'Social Game', 'Game Changer'),
(34, 'Physical Challenge', 'Mental Test', 'Power Shift'),
(35, 'Social Challenge', 'Endurance Game', 'Wild Card'),
(36, 'Mental Challenge', 'Physical Game', 'Game Breaker'),
(37, 'Endurance Challenge', 'Social Test', 'Power Move'),
(38, 'Physical Challenge', 'Mental Game', 'Wild Twist'),
(39, 'Social Challenge', 'Endurance Game', 'Game Changer'),
(40, 'Mental Challenge', 'Physical Test', 'Power Shift'),
(41, 'Endurance Challenge', 'Social Game', 'Wild Card'),
(42, 'Physical Challenge', 'Mental Test', 'Game Breaker'),
(43, 'Social Challenge', 'Endurance Game', 'Power Move'),
(44, 'Mental Challenge', 'Physical Game', 'Wild Twist'),
(45, 'Endurance Challenge', 'Social Test', 'Game Changer'),
(46, 'Physical Challenge', 'Mental Game', 'Power Shift'),
(47, 'Social Challenge', 'Endurance Game', 'Wild Card'),
(48, 'Mental Challenge', 'Physical Test', 'Game Breaker'),
(49, 'Endurance Challenge', 'Social Game', 'Power Move'),
(50, 'Physical Challenge', 'Mental Test', 'Wild Twist'),
(51, 'Social Challenge', 'Endurance Game', 'Game Changer'),
(52, 'Mental Challenge', 'Physical Game', 'Power Shift'),
(53, 'Endurance Challenge', 'Social Test', 'Wild Card'),
(54, 'Physical Challenge', 'Mental Game', 'Game Breaker'),
(55, 'Social Challenge', 'Endurance Game', 'Power Move'),
(56, 'Mental Challenge', 'Physical Test', 'Wild Twist'),
(57, 'Endurance Challenge', 'Social Game', 'Game Changer'),
(58, 'Physical Challenge', 'Mental Test', 'Power Shift'),
(59, 'Social Challenge', 'Endurance Game', 'Wild Card'),
(60, 'Mental Challenge', 'Physical Game', 'Game Breaker'),
(61, 'Endurance Challenge', 'Social Test', 'Power Move'),
(62, 'Physical Challenge', 'Mental Game', 'Wild Twist'),
(63, 'Social Challenge', 'Endurance Game', 'Game Changer'),
(64, 'Mental Challenge', 'Physical Test', 'Power Shift'),
(65, 'Social Challenge', 'Endurance Game', 'Wild Card'),
(66, 'Mental Challenge', 'Physical Game', 'Game Breaker'),
(67, 'Endurance Challenge', 'Social Test', 'Power Move'),
(68, 'Physical Challenge', 'Mental Game', 'Wild Twist'),
(69, 'Social Challenge', 'Endurance Game', 'Game Changer'),
(70, 'Mental Challenge', 'Physical Test', 'Power Shift'),
(71, 'Social Challenge', 'Endurance Game', 'Wild Card'),
(72, 'Mental Challenge', 'Physical Game', 'Game Breaker'),
(73, 'Endurance Challenge', 'Social Test', 'Power Move'),
(74, 'Physical Challenge', 'Mental Game', 'Wild Twist'),
(75, 'Social Challenge', 'Endurance Game', 'Game Changer'),
(76, 'Mental Challenge', 'Physical Test', 'Power Shift'),
(77, 'Social Challenge', 'Endurance Game', 'Wild Card'),
(78, 'Mental Challenge', 'Physical Game', 'Game Breaker'),
(79, 'Endurance Challenge', 'Social Test', 'Power Move'),
(80, 'Physical Challenge', 'Mental Game', 'Wild Twist'),
(81, 'Social Challenge', 'Endurance Game', 'Game Changer'),
(82, 'Mental Challenge', 'Physical Test', 'Power Shift'),
(83, 'Social Challenge', 'Endurance Game', 'Wild Card'),
(84, 'Mental Challenge', 'Physical Game', 'Game Breaker'),
(85, 'Endurance Challenge', 'Social Test', 'Power Move'),
(86, 'Physical Challenge', 'Mental Game', 'Wild Twist'),
(87, 'Social Challenge', 'Endurance Game', 'Game Changer'),
(88, 'Mental Challenge', 'Physical Test', 'Power Shift'),
(89, 'Social Challenge', 'Endurance Game', 'Wild Card'),
(90, 'Mental Challenge', 'Physical Game', 'Game Breaker'),
(91, 'Endurance Challenge', 'Social Test', 'Power Move'),
(92, 'Physical Challenge', 'Mental Game', 'Wild Twist'),
(93, 'Social Challenge', 'Endurance Game', 'Game Changer'),
(94, 'Mental Challenge', 'Physical Test', 'Power Shift'),
(95, 'Social Challenge', 'Endurance Game', 'Wild Card'),
(96, 'Mental Challenge', 'Physical Game', 'Game Breaker'),
(97, 'Endurance Challenge', 'Social Test', 'Power Move'),
(98, 'Physical Challenge', 'Mental Game', 'Wild Twist'),
(99, 'Social Challenge', 'Endurance Game', 'Game Changer'),
(100, 'Mental Challenge', 'Physical Test', 'Power Shift');
